version: '3'
services:
  server: 
    build: ./server 
    ports:
      - "3000:3000" 
    volumes:
      - ./server:/usr/src/app 
      #- E:\STUDY\2024 Spring\CS411\A25-Team-Project\client:\app
    environment:
      - NODE_ENV=production 

      
  client: 
    build: ./client 
    ports:
      - "80:80" 
    depends_on:
        - server