version: '3'
services:
  server: 
    build: ./server 
    ports:
      - "3000:3000" 
    volumes:
      - ./server:/usr/src/app 
    environment:
      - NODE_ENV=production 
      
      
  client: 
    build: ./client 
    ports:
      - "80:80" 
    depends_on:
        - server